### ISSUE TITLE
DMAs/RTDMAs to multiple people?

### ISSUE THREAD

**Issue by Amaikokonut** [AlbianWarp/AlbianWarpServer#23]
While we've talked about implementing a group feature, do you think it might be quicker/easier in the meantime to do something like allowing commas (or another delimiter) used in the 'aw_recipient' field to separate multiple usernames and then have the server parse and send a copy of that RT/DMA to each user?

**Comment by KeyboardInterrupt** [comment]
This could easily be done and should not be to complicated, It could be a good first issue for someone trying to get their feet wet with the python Stuff.

This is the function/file that would need to be modified.
https://github.com/AlbianWarp/AlbianWarpServer/blob/master/warpserver/resource/message.py#L20-L31

A good delimiter character would be `,` as it is not allowed inside of user names.

Questions that come to my mind:
- What could/should this Feature be used for?
- What should happen if one of the recipients does not exist?
- How many recipients are allowed to be passed this way?
- What should happen if that number is exceeded?

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
