### ISSUE TITLE
User Invisibility

### ISSUE THREAD

**Issue by Amaikokonut** [AlbianWarp/AlbianWarpServer#24]
It would be neat if somewhere down the line a user could choose to 'appear offline' so they don't show up as online in the contacts of others, but can still send and receive messages, chat requests, creatures, etc.

Implementing this in a way that users can't see through might be very challenging and potentially require rewriting a lot of stuff, so it's probably best saved for when we are overhauling other stuff like server-based friend/foe lists. But we can talk about it here.

As things currently stand, simply removing an "invisible" user from the public Online Users list would come at the cost of that user being able to use chat functions (and other RTDMAs), receive randomly-sent creatures, or receive creatures through portals. Since people can still send and receive messages and creatures regardless of online status, enabling something like this in the meantime might be better than nothing? It would depend on how in-demand of a feature this becomes.

**Comment by KeyboardInterrupt** [comment]
This is made obsolete by the Switch to ReBabel
